# Generated by Django 2.2.7 on 2019-11-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191127_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publicado',)},
        ),
    ]
