# Generated by Django 2.2.7 on 2019-11-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190526_1630'),
        ('blog', '0004_auto_20191127_2024'),
    ]

    operations = [
    ]
